In [1]:
import pandas as pd
import numpy as numpy
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
%pip install matplotlib #para graficar
%pip install seaborn #para graficar igual

***Carga de archivo XLSX***

In [5]:
#Carga desde un archivo .xlsx sin indice
df =pd.read_excel('Antigüedad de saldos 17.03.2023.xlsx')
df

,No. CLIENTE,NOMBRE,FACTURA,FECHA_FACTURA,FECHA_VENCIMIENTO,MONTO ADEUDADO
0,6401,DONGA HWASUNG MEXICO,F40238,2023-02-24,2023-03-26,97485.94
1,6401,DONGA HWASUNG MEXICO,F40353,2023-03-14,2023-04-13,97485.94
2,4598,PROVEEDORA DE SEGURIDAD INDUSTRIAL DEL GOLFO,F40352,2023-03-14,2023-04-13,64916.21
3,3930,INDUSTRIAS LANCERMEX,F40217,2023-02-23,2023-03-25,52715.74
4,4712,HELVEX,F40173,2023-02-17,2023-04-03,50639.80
...,...,...,...,...,...,...
159,856,CENTRO DE INVESTIGACION Y DE ESTUDIOS AVANZADO...,F40055,2023-01-31,2023-01-31,56.00
160,5926,PÚBLICO EN GENERAL,NV00777,2023-03-07,2023-03-07,45.00
161,5926,PÚBLICO EN GENERAL,NV00778,2023-03-09,2023-03-09,40.00
162,5926,PÚBLICO EN GENERAL,NV00779,2023-03-09,2023-03-09,24.01
163,8429,FISHERS QUERETARO,F38248,2022-05-27,2022-05-27,19.94

***Filtros básicos para variables cualitativas***

In [6]:
#Filtro por objeto
#Agarrar un dato de una columna
filtro1=[df[df['NOMBRE']=="INDUSTRIAS LANCERMEX"],
         df[df["NOMBRE"]=="DONGA HWASUNG MEXICO"]]
filtro1

[   No. CLIENTE                NOMBRE FACTURA FECHA_FACTURA FECHA_VENCIMIENTO  \
 3         3930  INDUSTRIAS LANCERMEX  F40217    2023-02-23        2023-03-25
 12        3930  INDUSTRIAS LANCERMEX  F40114    2023-02-09        2023-03-11

     MONTO ADEUDADO
 3         52715.74
 12        35143.82  ,
    No. CLIENTE                NOMBRE FACTURA FECHA_FACTURA FECHA_VENCIMIENTO  \
 0         6401  DONGA HWASUNG MEXICO  F40238    2023-02-24        2023-03-26
 1         6401  DONGA HWASUNG MEXICO  F40353    2023-03-14        2023-04-13
 43        6401  DONGA HWASUNG MEXICO  F40320    2023-03-08        2023-04-07
 51        6401  DONGA HWASUNG MEXICO  F40253    2023-02-27        2023-03-29

     MONTO ADEUDADO
 0         97485.94
 1         97485.94
 43        10759.00
 51         9396.00  ]

In [8]:
#Analizar categorías de una columna, para saber cuantos elemtos hay de cada categoría
categorias=df.groupby(['NOMBRE'])['NOMBRE'].count()
categorias

NOMBRE
ABASTECEDORA GOURMET                            1
ADVANEX DE MEXICO                               1
AIRBUS HELICOPTERS MEXICO QUERETARO             2
ALIMENTOS GOURMET DEL BAJIO                     1
ANA BARBARA CRUZ PALACIOS                       1
                                               ..
TERMOFORMADOS                                   1
TRANSPORTADORES Y FABRICACIONES INDUSTRIALES    3
TRATAMIENTOS TERMICOS DE QUERETARO              1
UCH COMERCIAL                                   1
VINILOS                                         3
Name: NOMBRE, Length: 97, dtype: int64

In [9]:
#Filtro por filas y no por columnas
#filtro2=df.iloc[3:10,:]   Filas consecutivas
filtro2=df.iloc[ [8,24,100] , :]  #Filas no consecutivas
filtro2

,No. CLIENTE,NOMBRE,FACTURA,FECHA_FACTURA,FECHA_VENCIMIENTO,MONTO ADEUDADO
8,644,CLAVOS NACIONALES C.N,F40340,2023-03-13,2023-05-12,45216.34
24,8708,TE.MEX AUTOMOTIVE,F40183,2023-02-20,2023-03-13,22956.40
100,3926,PRODUCTOS PENNSYLVANIA,F40357,2023-03-14,2023-04-13,2756.16

In [10]:
#Filtro por columnas
filtro3=df.iloc[ : , 1:3] #Columnas consecutivas
#filtro3=df.iloc[ : ,[1,4,6]] #Columnas no consecutivas
filtro3

                                                NOMBRE  FACTURA
0                                 DONGA HWASUNG MEXICO   F40238
1                                 DONGA HWASUNG MEXICO   F40353
2         PROVEEDORA DE SEGURIDAD INDUSTRIAL DEL GOLFO   F40352
3                                 INDUSTRIAS LANCERMEX   F40217
4                                               HELVEX   F40173
..                                                 ...      ...
159  CENTRO DE INVESTIGACION Y DE ESTUDIOS AVANZADO...   F40055
160                                 PÚBLICO EN GENERAL  NV00777
161                                 PÚBLICO EN GENERAL  NV00778
162                                 PÚBLICO EN GENERAL  NV00779
163                                  FISHERS QUERETARO   F38248

[164 rows x 2 columns]

In [ ]:
#Para establecer una columna como índice
df1=pd.read_excel('Antigüedad de saldos 17.03.2023.xlsx', index_col=1) 
df1

,No. CLIENTE,FACTURA,FECHA_FACTURA,FECHA_VENCIMIENTO,MONTO ADEUDADO
NOMBRE,,,,,
DONGA HWASUNG MEXICO,6401,F40238,2023-02-24,2023-03-26,97485.94
DONGA HWASUNG MEXICO,6401,F40353,2023-03-14,2023-04-13,97485.94
PROVEEDORA DE SEGURIDAD INDUSTRIAL DEL GOLFO,4598,F40352,2023-03-14,2023-04-13,64916.21
INDUSTRIAS LANCERMEX,3930,F40217,2023-02-23,2023-03-25,52715.74
HELVEX,4712,F40173,2023-02-17,2023-04-03,50639.80
...,...,...,...,...,...
CENTRO DE INVESTIGACION Y DE ESTUDIOS AVANZADOS DEL INSTITUTO POLITECNICO NACIONAL,856,F40055,2023-01-31,2023-01-31,56.00
PÚBLICO EN GENERAL,5926,NV00777,2023-03-07,2023-03-07,45.00
PÚBLICO EN GENERAL,5926,NV00778,2023-03-09,2023-03-09,40.00
PÚBLICO EN GENERAL,5926,NV00779,2023-03-09,2023-03-09,24.01
FISHERS QUERETARO,8429,F38248,2022-05-27,2022-05-27,19.94

In [ ]:
#Paso 2: Aplicamos filtro de filas vs columnas
filtro4=df1.loc[["HELVEX","DONGA HWASUNG MEXICO"],["MONTO ADEUDADO"]]
filtro4

                      MONTO ADEUDADO
NOMBRE
HELVEX                      50639.80
DONGA HWASUNG MEXICO        97485.94
DONGA HWASUNG MEXICO        97485.94
DONGA HWASUNG MEXICO        10759.00
DONGA HWASUNG MEXICO         9396.00

In [19]:
filtro5=df.head()
filtro5

,No. CLIENTE,NOMBRE,FACTURA,FECHA_FACTURA,FECHA_VENCIMIENTO,MONTO ADEUDADO
0,6401,DONGA HWASUNG MEXICO,F40238,2023-02-24,2023-03-26,97485.94
1,6401,DONGA HWASUNG MEXICO,F40353,2023-03-14,2023-04-13,97485.94
2,4598,PROVEEDORA DE SEGURIDAD INDUSTRIAL DEL GOLFO,F40352,2023-03-14,2023-04-13,64916.21
3,3930,INDUSTRIAS LANCERMEX,F40217,2023-02-23,2023-03-25,52715.74
4,4712,HELVEX,F40173,2023-02-17,2023-04-03,50639.80

In [25]:
#Filtro por terminal
filtro6=df.tail()
filtro6

,No. CLIENTE,NOMBRE,FACTURA,FECHA_FACTURA,FECHA_VENCIMIENTO,MONTO ADEUDADO
159,856,CENTRO DE INVESTIGACION Y DE ESTUDIOS AVANZADO...,F40055,2023-01-31,2023-01-31,56.00
160,5926,PÚBLICO EN GENERAL,NV00777,2023-03-07,2023-03-07,45.00
161,5926,PÚBLICO EN GENERAL,NV00778,2023-03-09,2023-03-09,40.00
162,5926,PÚBLICO EN GENERAL,NV00779,2023-03-09,2023-03-09,24.01
163,8429,FISHERS QUERETARO,F38248,2022-05-27,2022-05-27,19.94

***FILTROS BASICOS PARA VARIABLES CUANTITATIVAS***

In [17]:
#Filtro por comparacion
filtro7=df[df["MONTO ADEUDADO"] > 70000]
filtro7

,No. CLIENTE,NOMBRE,FACTURA,FECHA_FACTURA,FECHA_VENCIMIENTO,MONTO ADEUDADO
0,6401,DONGA HWASUNG MEXICO,F40238,2023-02-24,2023-03-26,97485.94
1,6401,DONGA HWASUNG MEXICO,F40353,2023-03-14,2023-04-13,97485.94

FILTROS BÁSICOS CON CONECTORES LÓGICOS

In [ ]:
#Filtro Y room type
filtro8=df[(df["MONTO ADEUDADO"]<6000)&(df["FECHA_FACTURA"]=="2023-03-14")]
filtro8

,No. CLIENTE,NOMBRE,FACTURA,FECHA_FACTURA,FECHA_VENCIMIENTO,MONTO ADEUDADO
85,409,CONSTRUCCIONES ELECTROMECANICAS Y SERVICIOS IN...,F40359,2023-03-14,2023-03-14,4292.00
96,3926,PRODUCTOS PENNSYLVANIA,F40358,2023-03-14,2023-04-13,3368.64
100,3926,PRODUCTOS PENNSYLVANIA,F40357,2023-03-14,2023-04-13,2756.16
101,5926,PÚBLICO EN GENERAL,F40362,2023-03-14,2023-03-14,2694.95
113,2216,FRESCOPACK,F40355,2023-03-14,2023-03-14,1682.00
132,1284,TERMOFORMADOS,F40349,2023-03-14,2023-04-13,799.24
135,8872,GABRIELA GARCIA SANCHEZ,F40360,2023-03-14,2023-03-14,754.00
139,8228,UCH COMERCIAL,F40365,2023-03-14,2023-03-14,702.96

In [ ]:
#Filtro o 5 host within a day 
filtro9=df[(df["MONTO ADEUDADO"]<6000)| (df["FECHA_FACTURA"]=="2023-03-14")]
filtro9

,No. CLIENTE,NOMBRE,FACTURA,FECHA_FACTURA,FECHA_VENCIMIENTO,MONTO ADEUDADO
1,6401,DONGA HWASUNG MEXICO,F40353,2023-03-14,2023-04-13,97485.94
2,4598,PROVEEDORA DE SEGURIDAD INDUSTRIAL DEL GOLFO,F40352,2023-03-14,2023-04-13,64916.21
9,644,CLAVOS NACIONALES C.N,F40351,2023-03-14,2023-05-13,45216.34
10,3937,RICHALUM,F40361,2023-03-14,2023-03-14,42880.05
36,417,COVEMEX,F40354,2023-03-14,2023-03-29,15843.28
...,...,...,...,...,...,...
159,856,CENTRO DE INVESTIGACION Y DE ESTUDIOS AVANZADO...,F40055,2023-01-31,2023-01-31,56.00
160,5926,PÚBLICO EN GENERAL,NV00777,2023-03-07,2023-03-07,45.00
161,5926,PÚBLICO EN GENERAL,NV00778,2023-03-09,2023-03-09,40.00
162,5926,PÚBLICO EN GENERAL,NV00779,2023-03-09,2023-03-09,24.01
163,8429,FISHERS QUERETARO,F38248,2022-05-27,2022-05-27,19.94

In [ ]:
#Filtro not baño
filtro10=df[~(df["MONTO ADEUDADO"]>=6000)] #Niega todo
filtro10

,No. CLIENTE,NOMBRE,FACTURA,FECHA_FACTURA,FECHA_VENCIMIENTO,MONTO ADEUDADO
70,1852,ITW POLY MEX,F40201,2023-02-22,2023-03-24,5967.85
71,8316,ANA BARBARA CRUZ PALACIOS,F40379,2023-03-16,2023-03-31,5827.84
72,8787,ARMANDO VIDAURRETA PEÑA,F39769,2022-12-14,2022-12-14,5800.00
73,2768,CEREALES Y PASTAS,F40215,2023-02-22,2023-03-24,5660.80
74,1831,DISTRIBUCIONES Y REPRESENTACIONES CALORA,F40316,2023-03-08,2023-04-22,5502.81
...,...,...,...,...,...,...
159,856,CENTRO DE INVESTIGACION Y DE ESTUDIOS AVANZADO...,F40055,2023-01-31,2023-01-31,56.00
160,5926,PÚBLICO EN GENERAL,NV00777,2023-03-07,2023-03-07,45.00
161,5926,PÚBLICO EN GENERAL,NV00778,2023-03-09,2023-03-09,40.00
162,5926,PÚBLICO EN GENERAL,NV00779,2023-03-09,2023-03-09,24.01
163,8429,FISHERS QUERETARO,F38248,2022-05-27,2022-05-27,19.94

In [27]:
#Convertir archivo  filtrado a CSV
filtro10.to_csv("Entregable1.csv")